default:
  image: alpine

before_script:
  - apk add cmake boost-unit_test_framework boost-dev boost-static ninja g++ gcovr

build:
  stage: build
  script:
    - mkdir build/
    - cd build/
    - CXXFLAGS=-coverage cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - cd build/
    - ctest -j$(nproc) . --output-on-failure
    - mkdir coverage
    - gcovr -r .. --exclude '.*apps/.*' -j$(nproc) --html --html-title bibtex-spirit --html-details -o coverage/report.html -s
  coverage: '/lines:\s+(\d+\.\d+|\d+)%/'
  artifacts:
    paths:
      - build/coverage
