os: linux
dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - cmake
      - g++
      - libboost-all-dev
      - ninja-build
install:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
script:
  - mkdir build/
  - cd build/
  - CXXFLAGS=-coverage cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - ctest -j$(nproc) . --output-on-failure

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token=${COVERALLS_TOKEN} coverage.info
  - bash <(curl -s https://codecov.io/bash)

